# Generated by Django 2.2.1 on 2019-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhistory',
            name='happyLevel',
            field=models.IntegerField(default=0),
        ),
    ]
